### ISSUE TITLE
Flat Lander - Header Improvements

### ISSUE THREAD

**Issue by BradKriss** [BrandXads/leaf-landers#15]
Flat lander looks great overall. Lets polish it some more today to get it 100%

- Instead of Fall savings event text on the left lets copy what DA did
- When form validates it breaks style. The 50% fields get pushed onto their own line.
- where it says over 200,000 customers that text needs to get a lil bigger, take up a wider area, less line height, and less border width.

**Comment by afreebern** [comment]
fixed all
