### ISSUE TITLE
Darken Hero Backgrounds

### ISSUE THREAD

**Issue by BradKriss** [BrandXads/leaf-landers#24]
I was just playing with the video hero in dev tools and applying a dark overlay (`rgba(0,0,0,.3`) makes the text way more readable. Video still looks good and text might look a lot better without the drop shadow. 

Lets play around with this Monday

**Comment by BradKriss** [comment]
I didn't bother stretching the overlaying div. it's too late for that shit, just messing around

![image](https://user-images.githubusercontent.com/7452215/45912705-da2ec180-bdf3-11e8-9918-9d06a3ecb902.png)

**Comment by afreebern** [comment]
mine
