### ISSUE TITLE
Scroll Page When Keyboard is Open

### ISSUE THREAD

**Issue by BradKriss** [BrandXads/leaf-landers#35]
Can listen to the window resizing

https://stackoverflow.com/a/50384891

@harlanmang also had a good idea of using the jQuery visible library.

When an input has a `:focus` state, we can check to make sure the input is `.visible()`

**Comment by BradKriss** [comment]
@harlanmang @afreebern Like to see you guys take a stab at this today

**Comment by harlanmang** [comment]
i broke it. Can push to own branch if we want to do this as a group.

**Comment by BradKriss** [comment]
Since all the inputs are ID'd could use JS

sudo code but should be able to do something like this, no?

```javascript
$.('#element').on('focus',  function() {
   if( ! $(this).visable() ) {
      $(this).scrollIntoView()
   }
});
```

**Comment by BradKriss** [comment]
Classes, would prob work the same

```javascript
$.('.input').on('focus',  function() {
   if( ! $(this).visable() ) {
      $(this).scrollIntoView()
   }
});
```

**Comment by BradKriss** [comment]
This library looks like it could be a good way to streamline to code.

https://www.npmjs.com/package/scroll-into-view-if-needed/v/1.5.0

**Comment by afreebern** [comment]
boom.
