### ISSUE TITLE
Fix privacy link

### ISSUE THREAD

**Issue by afreebern** [BrandXads/leaf-landers#4]
fix privacy link on forms

**Comment by BradKriss** [comment]
I'm working on creating the PP now

**Comment by BradKriss** [comment]
@afreebern Doc is ready (attached) -> need to convert it to html

You can see how it was done for TBD as reference: https://github.com/BrandXads/todays-best-deals/blob/master/resources/views/privacy.blade.php

Basically just header tag section headers and wrap paragraphs in p's

(emails and links subject to change but lets get doc live and those are easy edits to make)
[Guard My Gutter - Privacy Policy.docx](https://github.com/BrandXads/leaf-landers/files/2398205/Guard.My.Gutter.-.Privacy.Policy.docx)
