### ISSUE TITLE
Form Validation Overhaul

### ISSUE THREAD

**Issue by BradKriss** [BrandXads/leaf-landers#50]
Here's some good reads on form validation UX

https://designmodo.com/ux-form-validation/
https://medium.com/@andrew.burton/form-validation-best-practices-8e3bec7d0549
https://www.smashingmagazine.com/2017/05/better-form-design-one-thing-per-page/

Lets mock up some improved error states, maybe using tooltips, or giving more space. Lets also implement what validation we can in real time.

I can also create an API endpoint for the email validation, so that can be done in real time, I can also improve error the messages passed back server side.

**Comment by afreebern** [comment]
done. all landers have reactive form validation
